services:
   backendapi:
      image: openops/fmbackendapi:0.0.4
      container_name: backendapi
      ports:
         - "$backendapi_port:8080"
      environment:
         dbServerName: "$dbServerName"
         dbName: "$dbName"
         dbUserName: "$dbUserName"
         dbPassword: "$dbPassword"

   frontendapi:
      image: openops/fmfrontendapi:0.0.3
      container_name: frontendapi
      depends_on:
         backendapi:
            condition: service_started
      ports:
         - "$frontendapi_port:5000"
      environment:
         secret: "$secret"
         host_ip: "$host_ip"
         backendapi_port: "$backendapi_port"
