services:
   backendapi:
      image: backendapi:latest
      container_name: backendapi
      ports:
         - "$backendapi_port:80"
      environment:
         dbServerName: "$dbServerName"
         dbName: "$dbName"
         dbUserName: "$dbUserName"
         dbPassword: "$dbPassword"

   frontendapi:
      image: "frontendapi:latest"
      container_name: frontendapi
      depends_on:
         backendapi:
            condition: service_started
      ports:
         - "$frontendapi_port:5000"
      environment:
         secret: "$secret"
         host_ip: "$host_ip"
         backendapi_port: "$backendapi_port"
